-- IDIS Collectible Experience Platform v40
-- Run in a fresh Supabase project SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  brand jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('owner','admin','editor','viewer')),
  created_at timestamptz not null default now(),
  primary key (organization_id,user_id)
);

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  slug text not null,
  name text not null,
  starts_on date,
  ends_on date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (organization_id,slug)
);

create table if not exists public.collectibles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  campaign_id uuid references public.campaigns(id) on delete set null,
  slug text not null unique,
  name text not null,
  year integer,
  event_start date,
  event_end date,
  location text,
  image_url text,
  experience_type text not null default 'parallax',
  experience_config jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_collectibles (
  user_id uuid not null references auth.users(id) on delete cascade,
  collectible_id uuid not null references public.collectibles(id) on delete cascade,
  collected_at timestamptz not null default now(),
  claim_source text not null default 'scan',
  metadata jsonb not null default '{}'::jsonb,
  primary key (user_id,collectible_id)
);

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  organization_id uuid references public.organizations(id) on delete set null,
  campaign_id uuid references public.campaigns(id) on delete set null,
  collectible_id uuid references public.collectibles(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  anonymous_id text,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_events_created_idx on public.activity_events(created_at desc);
create index if not exists activity_events_type_idx on public.activity_events(event_type);
create index if not exists user_collectibles_collected_idx on public.user_collectibles(collected_at desc);
create index if not exists activity_events_organization_idx on public.activity_events(organization_id);
create index if not exists activity_events_campaign_idx on public.activity_events(campaign_id);
create index if not exists activity_events_collectible_idx on public.activity_events(collectible_id);
create index if not exists activity_events_user_idx on public.activity_events(user_id);
create index if not exists collectibles_organization_idx on public.collectibles(organization_id);
create index if not exists collectibles_campaign_idx on public.collectibles(campaign_id);
create index if not exists organization_members_user_idx on public.organization_members(user_id);
create index if not exists user_collectibles_collectible_idx on public.user_collectibles(collectible_id);

create schema if not exists private;

create or replace function private.has_org_role(target_org uuid, allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.organization_members m
    where m.organization_id = target_org
      and m.user_id = auth.uid()
      and m.role = any(allowed_roles)
  );
$$;

grant usage on schema private to anon, authenticated;
grant execute on function private.has_org_role(uuid,text[]) to anon, authenticated;

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.organization_members enable row level security;
alter table public.campaigns enable row level security;
alter table public.collectibles enable row level security;
alter table public.user_collectibles enable row level security;
alter table public.activity_events enable row level security;

-- Public catalog read.
drop policy if exists "public read organizations" on public.organizations;
create policy "public read organizations" on public.organizations for select using (true);
drop policy if exists "public read active campaigns" on public.campaigns;
create policy "public read active campaigns" on public.campaigns for select using (active or private.has_org_role(organization_id,array['owner','admin','editor','viewer']));
drop policy if exists "public read active collectibles" on public.collectibles;
create policy "public read active collectibles" on public.collectibles for select using (active or private.has_org_role(organization_id,array['owner','admin','editor','viewer']));

-- Own profile.
drop policy if exists "own profile select" on public.profiles;
create policy "own profile select" on public.profiles for select using ((select auth.uid())=user_id);
drop policy if exists "own profile insert" on public.profiles;
create policy "own profile insert" on public.profiles for insert with check ((select auth.uid())=user_id);
drop policy if exists "own profile update" on public.profiles;
create policy "own profile update" on public.profiles for update using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);

-- Membership visibility.
drop policy if exists "members see own memberships" on public.organization_members;
create policy "members see own memberships" on public.organization_members for select using ((select auth.uid())=user_id or private.has_org_role(organization_id,array['owner','admin']));

-- Collector owns their collection.
drop policy if exists "own collection select" on public.user_collectibles;
drop policy if exists "admin collection read" on public.user_collectibles;
drop policy if exists "collection select" on public.user_collectibles;
create policy "collection select" on public.user_collectibles for select using (
  (select auth.uid())=user_id
  or exists (
    select 1 from public.collectibles c
    where c.id = collectible_id
      and private.has_org_role(c.organization_id,array['owner','admin','editor'])
  )
);
drop policy if exists "own collection insert" on public.user_collectibles;
create policy "own collection insert" on public.user_collectibles for insert with check ((select auth.uid())=user_id);
drop policy if exists "own collection delete" on public.user_collectibles;
create policy "own collection delete" on public.user_collectibles for delete using ((select auth.uid())=user_id);

-- Basic telemetry. Anonymous inserts are allowed for this prototype. Move this behind an Edge Function for abuse controls at scale.
drop policy if exists "event insert" on public.activity_events;
create policy "event insert" on public.activity_events for insert with check (user_id is null or user_id=(select auth.uid()));
drop policy if exists "admin event read" on public.activity_events;
create policy "admin event read" on public.activity_events for select using (organization_id is not null and private.has_org_role(organization_id,array['owner','admin','editor']));

-- Client studio editing.
drop policy if exists "admin campaign insert" on public.campaigns;
create policy "admin campaign insert" on public.campaigns for insert with check (private.has_org_role(organization_id,array['owner','admin','editor']));
drop policy if exists "admin campaign update" on public.campaigns;
create policy "admin campaign update" on public.campaigns for update using (private.has_org_role(organization_id,array['owner','admin','editor'])) with check (private.has_org_role(organization_id,array['owner','admin','editor']));
drop policy if exists "admin collectible insert" on public.collectibles;
create policy "admin collectible insert" on public.collectibles for insert with check (private.has_org_role(organization_id,array['owner','admin','editor']));
drop policy if exists "admin collectible update" on public.collectibles;
create policy "admin collectible update" on public.collectibles for update using (private.has_org_role(organization_id,array['owner','admin','editor'])) with check (private.has_org_role(organization_id,array['owner','admin','editor']));
