(() => {
  const cfg=window.IDIS_PLATFORM_CONFIG||{}; let sb=null,session=null,org=null,email='';
  const $=q=>document.querySelector(q); const cloud=Boolean(cfg.supabaseUrl&&cfg.supabasePublishableKey);
  async function client(){if(sb)return sb;const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=m.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);return sb}
  function msg(t){$('#studio-msg').textContent=t||''} function authMsg(t){$('#studio-auth-msg').textContent=t||''}
  async function boot(){if(!cloud){$('#studio-setup').hidden=false;return}$('#studio-setup').hidden=true;const c=await client();const {data}=await c.auth.getSession();session=data.session;if(!session){$('#studio-login').hidden=false;return}await authorize()}
  async function authorize(){const c=await client();const {data,error}=await c.from('organization_members').select('role,organization:organizations(id,slug,name)').eq('user_id',session.user.id);if(error)throw error;const membership=(data||[]).find(x=>['owner','admin','editor'].includes(x.role));if(!membership){$('#studio-login').hidden=false;authMsg('This account does not have Studio access yet. Add it to organization_members.');return}org=membership.organization;$('#studio-login').hidden=true;$('#studio-dashboard').hidden=false;await load()}
  async function load(){const c=await client();const [{data:collectibles,error:e1},{count:collectorCount,error:e2},{count:eventCount,error:e3}]=await Promise.all([c.from('collectibles').select('*').eq('organization_id',org.id).order('created_at',{ascending:false}),c.from('user_collectibles').select('*',{count:'exact',head:true}),c.from('activity_events').select('*',{count:'exact',head:true}).eq('organization_id',org.id)]);if(e1||e2||e3)msg((e1||e2||e3).message);$('#stat-collectibles').textContent=(collectibles||[]).length;$('#stat-collectors').textContent=collectorCount||0;$('#stat-events').textContent=eventCount||0;const list=$('#studio-list');list.innerHTML=(collectibles||[]).map(x=>`<div class="row"><div><strong>${x.name}</strong><small>${x.slug} · ${x.location||'No location'} · ${x.active?'LIVE':'DRAFT'}</small></div><button data-edit='${x.id}'>Edit</button></div>`).join('')||'<p>No collectibles yet.</p>';list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit((collectibles||[]).find(x=>x.id===b.dataset.edit)))}
  function edit(x){$('#collectible-id').value=x.id;$('#collectible-slug').value=x.slug;$('#collectible-name').value=x.name;$('#collectible-year').value=x.year||'';$('#collectible-type').value=x.experience_type||'parallax';$('#collectible-location').value=x.location||'';$('#collectible-image').value=x.image_url||'';$('#collectible-config').value=JSON.stringify(x.experience_config||{},null,2);$('#collectible-active').checked=x.active!==false}
  $('#studio-email-form').onsubmit=async e=>{e.preventDefault();email=$('#studio-email').value.trim();try{const c=await client();const {error}=await c.auth.signInWithOtp({email,options:{emailRedirectTo:cfg.auth?.redirectUrl ? cfg.auth.redirectUrl.replace(/\/$/,'') + '/studio.html' : location.href.split('#')[0]}});if(error)throw error;$('#studio-email-form').hidden=true;$('#studio-code-form').hidden=false;authMsg('Sign-in email sent. Use the link, or enter the code if your template includes one.')}catch(err){authMsg(err.message)}};
  $('#studio-code-form').onsubmit=async e=>{e.preventDefault();try{const c=await client();const {data,error}=await c.auth.verifyOtp({email,token:$('#studio-code').value.trim(),type:'email'});if(error)throw error;session=data.session;await authorize()}catch(err){authMsg(err.message)}};
  $('#studio-refresh').onclick=load;
  $('#collectible-form').onsubmit=async e=>{e.preventDefault();try{let config=JSON.parse($('#collectible-config').value||'{}');const record={organization_id:org.id,slug:$('#collectible-slug').value.trim(),name:$('#collectible-name').value.trim(),year:Number($('#collectible-year').value)||null,experience_type:$('#collectible-type').value,location:$('#collectible-location').value.trim()||null,image_url:$('#collectible-image').value.trim()||null,experience_config:config,active:$('#collectible-active').checked,updated_at:new Date().toISOString()};const id=$('#collectible-id').value;const c=await client();let result=id?await c.from('collectibles').update(record).eq('id',id):await c.from('collectibles').insert(record);if(result.error)throw result.error;msg('Saved.');e.target.reset();$('#collectible-id').value='';$('#collectible-active').checked=true;$('#collectible-config').value='{}';await load()}catch(err){msg(err.message)}};
  boot().catch(err=>{console.error(err);$('#studio-setup').hidden=false;$('#studio-setup').innerHTML=`<h2>Studio error</h2><p>${err.message}</p>`});
})();
